#pragma once

#define LEVELSHIFT_DIR         3
#define ARM_SWITCH             6
#define SDA                    4
#define SCL                    5
#define GPS_EXTINT             27
#define SPI_MOSI                   9
#define SPI_MISO                   10
#define SPI_SCK                    11
#define IMU_CS                 14
#define BAROMETER_CS           13
#define RADIO_CS               0
#define RADIO_D0               1
#define RADIO_RESET            2
#define LED_DATA               12
#define EXPANSION_1            7
#define EXPANSION_2            15
#define SD_CMD                 18
#define SD_DATA_0              19
#define SD_DATA_1              20
#define SD_DATA_2              21
#define SD_DATA_3              22
#define SD_CLOCK               23
#define SERVO_POWER_ENABLE     8
#define SERVO_1                28
#define SERVO_2                29
#define SERVO_3                25
#define SERVO_4                24
#define SERVO_5                17
#define SERVO_6                16
#define BATTERY_SENSE          26
